//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escape_Room.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Escape_Room.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button_red {
            get {
                object obj = ResourceManager.GetObject("button_red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Door_1 {
            get {
                object obj = ResourceManager.GetObject("Door_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Door_3 {
            get {
                object obj = ResourceManager.GetObject("Door_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Door2__1_ {
            get {
                object obj = ResourceManager.GetObject("Door2__1_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap duck {
            get {
                object obj = ResourceManager.GetObject("duck", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap duck___Copy {
            get {
                object obj = ResourceManager.GetObject("duck___Copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EsacpeKey3 {
            get {
                object obj = ResourceManager.GetObject("EsacpeKey3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap escape_door {
            get {
                object obj = ResourceManager.GetObject("escape_door", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EscapeKey1__2_ {
            get {
                object obj = ResourceManager.GetObject("EscapeKey1__2_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EscapeKey2 {
            get {
                object obj = ResourceManager.GetObject("EscapeKey2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap feet {
            get {
                object obj = ResourceManager.GetObject("feet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap floor {
            get {
                object obj = ResourceManager.GetObject("floor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;scores&gt;
        ///  &lt;name&gt;Phaedra&lt;/name&gt;
        ///  &lt;score&gt;400&lt;/score&gt;
        ///  &lt;name&gt;Cleo&lt;/name&gt;
        ///  &lt;score&gt;500&lt;/score&gt;
        ///&lt;/scores&gt;.
        /// </summary>
        internal static string high {
            get {
                return ResourceManager.GetString("high", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap key {
            get {
                object obj = ResourceManager.GetObject("key", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream KeySound {
            get {
                return ResourceManager.GetStream("KeySound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;level&gt;
        ///  &lt;tasks&gt;
        ///    &lt;task&gt;
        ///      &lt;colour&gt;red&lt;/colour&gt;
        ///      &lt;x&gt;90&lt;/x&gt;
        ///      &lt;y&gt;60&lt;/y&gt;
        ///      &lt;width&gt;50&lt;/width&gt;
        ///      &lt;height&gt;50&lt;/height&gt;
        ///    &lt;/task&gt;
        ///    &lt;task&gt;
        ///      &lt;colour&gt;green&lt;/colour&gt;
        ///      &lt;x&gt;100&lt;/x&gt;
        ///      &lt;y&gt;600&lt;/y&gt;
        ///      &lt;width&gt;50&lt;/width&gt;
        ///      &lt;height&gt;50&lt;/height&gt;
        ///    &lt;/task&gt;
        ///    &lt;task&gt;
        ///      &lt;colour&gt;blue&lt;/colour&gt;
        ///      &lt;x&gt;1200&lt;/x&gt;
        ///      &lt;y&gt;600&lt;/y&gt;
        ///      &lt;width&gt;50&lt;/width&gt;
        ///      &lt;height&gt;50&lt;/height&gt;
        ///    &lt;/task&gt;
        ///  &lt;/tasks&gt;
        ///  &lt;walls&gt;
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level1 {
            get {
                return ResourceManager.GetString("level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;level&gt;
        ///  &lt;tasks&gt;
        ///    &lt;task&gt;
        ///      &lt;colour&gt;pink&lt;/colour&gt;
        ///      &lt;x&gt;100&lt;/x&gt;
        ///      &lt;y&gt;600&lt;/y&gt;
        ///      &lt;width&gt;50&lt;/width&gt;
        ///      &lt;height&gt;50&lt;/height&gt;
        ///    &lt;/task&gt;
        ///    &lt;task&gt;
        ///      &lt;colour&gt;paleturquiose&lt;/colour&gt;
        ///      &lt;x&gt;600&lt;/x&gt;
        ///      &lt;y&gt;60&lt;/y&gt;
        ///      &lt;width&gt;50&lt;/width&gt;
        ///      &lt;height&gt;50&lt;/height&gt;
        ///    &lt;/task&gt;
        ///    &lt;task&gt;
        ///      &lt;colour&gt;black&lt;/colour&gt;
        ///      &lt;x&gt;1000&lt;/x&gt;
        ///      &lt;y&gt;600&lt;/y&gt;
        ///      &lt;width&gt;50&lt;/width&gt;
        ///      &lt;height&gt;50&lt;/height&gt;
        ///    &lt;/task&gt;
        ///  &lt;/tasks&gt;
        ///  &lt;w [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level2 {
            get {
                return ResourceManager.GetString("Level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;level&gt;
        ///  &lt;tasks&gt;
        ///    &lt;task&gt;
        ///      &lt;colour&gt;yellow&lt;/colour&gt;
        ///      &lt;x&gt;300&lt;/x&gt;
        ///      &lt;y&gt;400&lt;/y&gt;
        ///      &lt;width&gt;50&lt;/width&gt;
        ///      &lt;height&gt;50&lt;/height&gt;
        ///    &lt;/task&gt;
        ///    &lt;task&gt;
        ///      &lt;colour&gt;lightgreen&lt;/colour&gt;
        ///      &lt;x&gt;1000&lt;/x&gt;
        ///      &lt;y&gt;300&lt;/y&gt;
        ///      &lt;width&gt;50&lt;/width&gt;
        ///      &lt;height&gt;50&lt;/height&gt;
        ///    &lt;/task&gt;
        ///    &lt;task&gt;
        ///      &lt;colour&gt;purple&lt;/colour&gt;
        ///      &lt;x&gt;1000&lt;/x&gt;
        ///      &lt;y&gt;500&lt;/y&gt;
        ///      &lt;width&gt;50&lt;/width&gt;
        ///      &lt;height&gt;50&lt;/height&gt;
        ///    &lt;/task&gt;
        ///  &lt;/tasks&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Level3 {
            get {
                return ResourceManager.GetString("Level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream LevelComplete {
            get {
                return ResourceManager.GetStream("LevelComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap map_1 {
            get {
                object obj = ResourceManager.GetObject("map_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap person {
            get {
                object obj = ResourceManager.GetObject("person", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rain {
            get {
                object obj = ResourceManager.GetObject("rain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spyglass {
            get {
                object obj = ResourceManager.GetObject("spyglass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sun {
            get {
                object obj = ResourceManager.GetObject("sun", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream TaskSound4 {
            get {
                return ResourceManager.GetStream("TaskSound4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream TaskSound5 {
            get {
                return ResourceManager.GetStream("TaskSound5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream TaskSound7 {
            get {
                return ResourceManager.GetStream("TaskSound7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream ThemeSound {
            get {
                return ResourceManager.GetStream("ThemeSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream wooden_stairs_1 {
            get {
                return ResourceManager.GetStream("wooden_stairs_1", resourceCulture);
            }
        }
    }
}
